// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVGEbE1trjkEoAm_tBsd2vzh5QVV4Vu2g',
    appId: '1:930362370585:web:906193f08dce3009631888',
    messagingSenderId: '930362370585',
    projectId: 'chatapp-820f1',
    authDomain: 'chatapp-820f1.firebaseapp.com',
    storageBucket: 'chatapp-820f1.appspot.com',
    measurementId: 'G-QN0779KSY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXEOTF2VvuY2X0bELWxhQYJAilBeVZr7o',
    appId: '1:930362370585:android:84631cccf1a42c22631888',
    messagingSenderId: '930362370585',
    projectId: 'chatapp-820f1',
    storageBucket: 'chatapp-820f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJfywanL_VMuUBsDaHA5yRUIUxhdaKNU',
    appId: '1:930362370585:ios:b52efee62f602d38631888',
    messagingSenderId: '930362370585',
    projectId: 'chatapp-820f1',
    storageBucket: 'chatapp-820f1.appspot.com',
    iosClientId: '930362370585-dsd8in6411ona1r5o7hemk6plbab2iom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJfywanL_VMuUBsDaHA5yRUIUxhdaKNU',
    appId: '1:930362370585:ios:b52efee62f602d38631888',
    messagingSenderId: '930362370585',
    projectId: 'chatapp-820f1',
    storageBucket: 'chatapp-820f1.appspot.com',
    iosClientId: '930362370585-dsd8in6411ona1r5o7hemk6plbab2iom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
